export const LOGIN = 'LOGIN';
export const LOGIN_FAILED_NOT_EXISTED = 'LOGIN_FAILED_NOT_EXISTED';
export const LOGIN_FAILED_NOT_MATCH = 'LOGIN_FAILED_NOT_MATCH';
export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER';
export const REGISTER_FAILED_EXISTED = 'REGISTER_FAILED_EXISTED';